export const properties = [
  {
    id: "01",
    name: "The Meridian Residences",
    city: "Mumbai",
    location: "Worli, Mumbai",
    price: "₹18.5 Cr",
    image: "/images/slide-1.png",
    type: "Residential",
    details: "4 BHK · 4200 sq.ft. · Sea View · Ready to Move",
    description: "A masterclass in modern Indian architecture, this residence is perfectly aligned with the celestial meridians to ensure peak energetic harmony. Featuring expansive sea views and bespoke interiors crafted by the finest artisans in Rajasthan.",
    beds: "4",
    baths: "5",
    sqft: "4,200",
  },
  {
    id: "02",
    name: "The Banyan Estate",
    city: "Delhi",
    location: "Chattarpur, Delhi",
    price: "₹14 Cr",
    image: "/images/slide-2.png",
    type: "Villas",
    details: "5 BHK · 1.5 Acre · Private Pool · Lush Greenery",
    description: "Nestled in the heart of Delhi's most exclusive farm belt, The Banyan Estate is a sanctuary of peace. This sprawling villa combines heritage aesthetics with ultra-modern amenities, all within a lush 1.5-acre private garden.",
    beds: "5",
    baths: "6",
    sqft: "12,000",
  },
  {
    id: "03",
    name: "Casa Del Mar",
    city: "Goa",
    location: "North Goa",
    price: "₹6.2 Cr",
    image: "/images/slide-3.png",
    type: "Villas",
    details: "4 BHK · Private Deck · Bougainvillea Courtyard",
    description: "A tribute to Indo-Portuguese architecture, Casa Del Mar offers a lifestyle of coastal elegance. With a private deck overlooking the Arabian Sea and a central courtyard filled with blooming bougainvillea, it's the ultimate retreat.",
    beds: "4",
    baths: "4",
    sqft: "3,800",
  },
  {
    id: "04",
    name: "Skyline Penthouses",
    city: "Hyderabad",
    location: "Jubilee Hills, Hyderabad",
    price: "₹9.8 Cr",
    image: "/images/slide-4.png",
    type: "Penthouses",
    details: "4 BHK · Infinity Plunge Pool · Panoramic Views",
    description: "Perched atop the highest point in Jubilee Hills, the Skyline Penthouses offer an unparalleled perspective of Hyderabad. Features include a private infinity plunge pool and triple-height glass walls that blur the line between sky and home.",
    beds: "4",
    baths: "5",
    sqft: "5,500",
  },
  {
    id: "05",
    name: "Eden Sky Villas",
    city: "Bangalore",
    location: "Indiranagar, Bangalore",
    price: "₹7.5 Cr",
    image: "/images/slide-5.png",
    type: "Villas",
    details: "3 BHK · Green Balconies · Modern Minimalist",
    description: "Eden Sky Villas redefines vertical living in Bangalore. Each floor is a self-contained sanctuary with wrap-around green balconies and open-plan layouts that maximize natural light and cross-ventilation.",
    beds: "3",
    baths: "3",
    sqft: "4,000",
  }
];
